[workspace]
resolver = "2"
members = [
    "crates/pipeql-core",
    "crates/pipeql-cli",
    "crates/pipeql-cffi",
    "crates/pipeql-wasm",
    "crates/pipeql-python",
    "crates/pipeql-lsp",
]

[workspace.package]
version = "1.1.7"
edition = "2021"
license = "MIT"
repository = "https://github.com/Flaxmbot/PipeQL"

[workspace.dependencies]
pipeql-core = { path = "crates/pipeql-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
incremental = true

[profile.dev.package."*"]
opt-level = 2

[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 4
strip = true
